#!/usr/bin/env Rscript

## Excel sheet intake {{{

# Intake of excel data
df_big <- read_excel("../data/pocus-survey.xlsx")

# Rename columns
rvar <- c(
"timestamp",
"email",
"consent",
"cohort",
"specialty",
"curriculum",
"experience",
"icu_num",
"comfort_dx",
"comfort_tx",
"interest_level",
"career_plan",
"cv1",
"cv1c",
"cv2",
"cv2c",
"cv3",
"cv3c",
"cv4",
"cv4c",
"cv5",
"cv5c",
"cv6",
"cv6c",
"cs1",
"cs1c",
"cs2",
"cs2c",
"cs3",
"cs3c",
"cf1",
"cf1c",
"cf2",
"cf2c",
"cf3",
"cf3c",
"cf4",
"cf4c",
"cf5",
"cf5c",
"vs1",
"vs1c",
"vs2",
"vs2c",
"vf1",
"vf1c",
"vf2",
"vf2c",
"vf3",
"vf3c",
"vf4",
"vf4c"
)

# Substitute current names for shorter labels
names(df_big) <- rvar
rm(rvar)

# Reorganized the class year status
df_big$cohort <- 
  recode(df_big$cohort, 
         "PGY-3" = "GRAD", 
         "PGY-2" = "PGY3", 
         "PGY-1" = "PGY2", 
         "July 2015" = "GRAD",
         "July 2016" = "PGY3",
         "July 2017" = "PGY2",
         "July 2018" = "PGY1")

# Reorder based on year 
df_big$cohort %<>% fct_relevel(., "PGY1", "PGY2", "PGY3", "GRAD")

# Identify number in each class total

n_GRAD <- 56
n_PGY3 <- 57
n_PGY2 <- 56
n_PGY1 <- 56

# }}}

## Correct answers {{{

# Generated by expert reviewers
questions <- c(
"cv1",
"cv2",
"cv3",
"cv4",
"cv5",
"cv6",
"cs1",
"cs2",
"cs3",
"cf1",
"cf2",
"cf3",
"cf4",
"cf5",
"vs1",
"vs2",
"vf1",
"vf2",
"vf3",
"vf4"
)

answers <- c(
"Parasternal long",
"Parasternal short",
"Subxiphoid",
"Parasternal short",
"Apical",
"Parasternal long",
"Right ventricle",
"Pericardial effusion",
"Left atrium",
"Normal (LVEF >40%)",
"Reduced (LVEF <40%)",
"Reduced (LVEF <40%)",
"Reduced (LVEF <40%)",
"Reduced (LVEF <40%)",
"IVC",
"IVC",
"Collapsible IVC",
"Aorta",
"Aorta",
"Non-Collapsible IVC"
)

question_type <- c(
"cv",
"cv",
"cv",
"cv",
"cv",
"cv",
"cs",
"cs",
"cs",
"cf",
"cf",
"cf",
"cf",
"cf",
"vs",
"vs",
"vf",
"vf",
"vf",
"vf"
)

quiz_guide <-
  bind_cols(question = questions, question_type = question_type) %>%
  bind_cols(., answers = answers)

# }}}
